apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-cluster-role
rules:
- apiGroups: [""]
  resources: ["services", "nodes"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
