apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-sa-admin
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-sa-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: default
roleRef:
  kind: Role 
  name: jenkins-sa-admin
  apiGroup: rbac.authorization.k8s.io